'use client';

import React from 'react';

export default function TermsOfServicePage() {
    const [showFullTerms, setShowFullTerms] = React.useState(false);

    return (
        <main className="pt-32 pb-24 px-6 w-full bg-white min-h-screen">
            <div className="max-w-4xl mx-auto">
                {/* Header */}
                <div className="mb-12 border-b border-gray-100 pb-8">
                    <h1 className="text-3xl md:text-5xl font-bold text-[#052e16] mb-4 tracking-tight">
                        Terms of Service & Risk Disclosure
                    </h1>
                    <p className="text-gray-500 font-medium">Last Updated: January 2026</p>
                </div>

                {/* Human Summary (Layer 1) */}
                <div className="space-y-12 text-gray-700 leading-relaxed font-light mb-16">

                    {/* Educational Purpose */}
                    <section>
                        <h2 className="text-xl md:text-2xl font-bold text-[#052e16] mb-4">
                            1. Educational Purpose Only
                        </h2>
                        <p className="text-lg">
                            Welmora is a calculator and educational tool, not a registered investment advisor, broker-dealer, or financial institution. All content, calculations, and inputs generated by this application are strictly for <strong>educational and informational purposes only</strong>. They do not constitute financial advice, investment recommendations, or a solicitation to buy or sell any assets.
                        </p>
                    </section>

                    {/* Market Risk */}
                    <section>
                        <h2 className="text-xl md:text-2xl font-bold text-[#052e16] mb-4">
                            2. Market Risk Disclosure
                        </h2>
                        <p className="text-lg">
                            Investments in securities, mutual funds, and other financial instruments are subject to <strong>market risk</strong>, including the possible loss of principal amount invested. Past performance is not indicative of future results. We are not responsible for any financial loss, damages, or missed opportunities resulting from decisions made based on Welmora's tools or data.
                        </p>
                    </section>

                    {/* Algorithmic Limitations */}
                    <section>
                        <h2 className="text-xl md:text-2xl font-bold text-[#052e16] mb-4">
                            3. Algorithmic Limitations
                        </h2>
                        <p className="text-lg">
                            Calculations are based on user inputs and standard mathematical assumptions (such as constant inflation rates or linear growth). Real-world markets are non-linear and unpredictable. The projections shown are theoretical examples and should not be treated as future guarantees.
                        </p>
                    </section>

                    {/* User Responsibility */}
                    <section>
                        <h2 className="text-xl md:text-2xl font-bold text-[#052e16] mb-4">
                            4. User Responsibility
                        </h2>
                        <p className="text-lg">
                            You acknowledge that you are solely responsible for your own financial decisions. We strongly recommend consulting with a SEBI-registered investment advisor or a qualified financial professional before making any investment decisions.
                        </p>
                    </section>

                </div>

                {/* The Divider & Toggle */}
                <div className="flex flex-col items-center justify-center py-12 border-t border-gray-200">
                    <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-6">Legal Contract</p>
                    <button
                        onClick={() => setShowFullTerms(!showFullTerms)}
                        className="px-8 py-3 bg-gray-50 hover:bg-gray-100 text-gray-900 font-semibold rounded-full border border-gray-200 transition-all duration-300 shadow-sm hover:shadow-md"
                    >
                        {showFullTerms ? "Collapse Legal Document" : "View Full Commercial Contract"}
                    </button>
                </div>

                {/* Long Form Contract (Layer 2) */}
                {showFullTerms && (
                    <div className="animate-in fade-in slide-in-from-top-4 duration-700 space-y-8 bg-gray-50/50 p-8 md:p-12 rounded-3xl border border-gray-100 text-sm leading-7 text-slate-600 font-normal">

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">1. PREAMBLE</h3>
                            <p>These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "You") and Welmora ("Company," "We," "Us"), a technology company incorporated under the laws of India. By accessing our website, mobile application, or API (collectively, the "Platform"), you agree to abide by these Terms. If you do not agree, you must immediately discontinue use of the Platform.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">2. DEFINITIONS</h3>
                            <ul className="list-disc pl-5 space-y-2">
                                <li><strong>"Calculators"</strong> refers to the SIP, SWP, FIRE, and EMI computing engines provided by Welmora.</li>
                                <li><strong>"Content"</strong> refers to all text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork, and computer code.</li>
                                <li><strong>"Algorithmic Output"</strong> refers to the mathematical projections generated by the Platform based on User Input.</li>
                            </ul>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">3. NATURE OF SERVICES (EDUCATIONAL DISCLAIMER)</h3>
                            <p><strong>3.1 No Financial Advice.</strong> The Platform is an educational tool designed to assist Users in understanding financial concepts through mathematical modeling. Welmora is not a SEBI-registered Investment Advisor, Portfolio Manager, or Broker-Dealer.</p>
                            <p className="mt-2"><strong>3.2 Hypothetical Projections.</strong> The outputs generated by our "FIRE Engine" and "SIP Solvers" are based on mathematical assumptions regarding inflation, market returns, and taxation. These are hypothetical scenarios and do not reflect actual market performance. Real-world returns will vary.</p>
                            <p className="mt-2"><strong>3.3 User Responsibility.</strong> You acknowledge that all investment decisions involve risk, including the loss of principal. You are solely responsible for your financial decisions. Welmora shall not be liable for any decision made or action taken in reliance on the information contained on this Platform.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">4. INTELLECTUAL PROPERTY RIGHTS</h3>
                            <p><strong>4.1 Ownership.</strong> The Platform, including its "Industrial Grade" logic, source code, and "Bento Grid" interface design, is owned and controlled by the Founders (Muad Rahman and Rohith CK).</p>
                            <p className="mt-2"><strong>4.2 License.</strong> We grant you a limited, non-exclusive, non-transferable license to use the Platform for personal, non-commercial financial planning.</p>
                            <p className="mt-2"><strong>4.3 Restrictions.</strong> You may not: (a) reverse engineer, decompile, or disassemble the Platform; (b) use any "spider," "scraper," or "robot" to access the Platform; (c) attempt to gain unauthorized access to our servers.</p>
                        </div>

                        <div className="p-6 bg-red-50/50 border border-red-100 rounded-xl">
                            <h3 className="text-lg font-bold text-red-900 mb-2 uppercase">5. LIMITATION OF LIABILITY</h3>
                            <p className="text-red-800">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL WELMORA, ITS FOUNDERS, AFFILIATES, OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES ARISING OUT OF OR IN CONNECTION WITH THE USE OF THE PLATFORM.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">6. INDEMNIFICATION</h3>
                            <p>You agree to defend, indemnify, and hold harmless Welmora, its Founders, officers, directors, employees, and agents from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms or your use of the Platform.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">7. GOVERNING LAW AND JURISDICTION</h3>
                            <p>These Terms shall be governed by and construed in accordance with the laws of India. Any dispute arising out of or in connection with these Terms, including any question regarding their existence, validity, or termination, shall be subject to the exclusive jurisdiction of the courts located in Hyderabad, Telangana.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">9. USER ACCOUNT SECURITY</h3>
                            <p>If you choose, or are provided with, a user name, password, or any other piece of information as part of our security procedures, you must treat such information as confidential. You acknowledge that your account is personal to you and agree not to provide any other person with access to this Service using your user name, password, or other security information. You agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">10. PROHIBITED CONDUCT</h3>
                            <p>You agree not to use the Platform:</p>
                            <ul className="list-disc pl-5 mt-2 space-y-1">
                                <li>In any way that violates any applicable federal, state, local, or international law or regulation.</li>
                                <li>To exploit, harm, or attempt to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</li>
                                <li>To transmit, or procure the sending of, any advertising or promotional material, including any "junk mail," "chain letter," "spam," or any other similar solicitation.</li>
                                <li>To impersonate or attempt to impersonate the Company, a Company employee, another user, or any other person or entity.</li>
                                <li>To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Platform, or which, as determined by us, may harm the Company or users of the Platform, or expose them to liability.</li>
                            </ul>
                            <p className="mt-2">Additionally, you agree not to:</p>
                            <ul className="list-disc pl-5 mt-2 space-y-1">
                                <li>Use the Platform in any manner that could disable, overburden, damage, or impair the site or interfere with any other party's use of the Platform.</li>
                                <li>Use any robot, spider, or other automatic device, process, or means to access the Platform for any purpose, including monitoring or copying any of the material on the Platform.</li>
                                <li>Introduce any viruses, trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.</li>
                            </ul>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">11. PAYMENT TERMS (FUTURE PROVISIONS)</h3>
                            <p>Welmora currently operates on a free-to-use model. However, we reserve the right to introduce subscription fees or premium features in the future. Any such changes will be communicated to you in advance. All payments made are non-refundable unless otherwise required by law.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">12. THIRD-PARTY LINKS</h3>
                            <p>The Platform may contain links to third-party websites or services that are not owned or controlled by Welmora. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services. You further acknowledge and agree that Welmora shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such websites or services.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">13. DISCLAIMER OF WARRANTIES</h3>
                            <p className="uppercase">YOUR USE OF THE PLATFORM, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE PLATFORM IS AT YOUR OWN RISK. THE PLATFORM, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE PLATFORM ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER THE COMPANY NOR ANY PERSON ASSOCIATED WITH THE COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE PLATFORM.</p>
                        </div>

                        <div className="p-6 bg-red-50/50 border border-red-100 rounded-xl">
                            <h3 className="text-lg font-bold text-red-900 mb-2 uppercase">14. FORCE MAJEURE</h3>
                            <p className="text-red-800">Welmora shall not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond Welmora's reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation (including "line-noise" interference), acts of God, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes, or shortages of transportation facilities, fuel, energy, labor or materials.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">15. CLASS ACTION WAIVER</h3>
                            <p className="uppercase">WHERE PERMITTED UNDER THE APPLICABLE LAW, YOU AND WELMORA AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION. UNLESS BOTH YOU AND WELMORA AGREE, NO ARBITRATOR OR JUDGE MAY CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS OR OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">16. SEVERABILITY & WAIVER</h3>
                            <p>If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect. No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term, and Welmora's failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision.</p>
                        </div>

                        <div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">17. ENTIRE AGREEMENT</h3>
                            <p>The Terms of Service and our Privacy Policy constitute the sole and entire agreement between you and Welmora regarding the Platform and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding the Platform.</p>
                        </div>

                    </div>
                )}
            </div>
        </main>
    );
}
